# --- Categories ADMET ---
categories_adme = {
    "Molecular Properties": ["Molecular Weight", "HBA", "HBD", "TPSA", "LogP", "Stereo Centers", "Solubility"],
    "Absorption": ["Caco-2", "Bioavailability", "HIA", "PAMPA", "Pgp"],
    "Distribution": ["BBB penetration", "VDss", "PPBR"],
    "Metabolism": ["CYP1A2 inhibitor", "CYP2C19 inhibitor", "CYP2C9 inhibitor", "CYP2D6 inhibitor", "CYP3A4 inhibitor", "CYP2C9 Substrate", "CYP2D6 Substrate", "CYP3A4 Substrate"],
    "Excretion": ["Clearance (Microsome)", "Clearance (Hepatocyte)", "Half Life"],
    "Toxicity": ["AMES", "DILI", "Carcinogenicity", "hERG", "Skin Reaction", "LD50", "ClinTox"], 
    "Other / Nuclear Receptor & Stress Response": ["NR-AR-LBD", "NR-AR", "NR-AhR", "NR-Aromatase", "NR-ER-LBD", "NR-ER", "NR-PPAR-gamma", "SR-ARE", "SR-ATAD5", "SR-HSE", "SR-MMP", "SR-p53"]
}

#map columns from adme_df to original_df
map_columns = {
    "Molecular Weight": "molecular_weight",
    "HBA": "hydrogen_bond_acceptors",
    "HBD": "hydrogen_bond_donors",
    "TPSA": "tpsa",
    "LogP": "logP",
    "Solubility": "Solubility_AqSolDB",
    "QED": "QED",
    "Stereo Centers": "stereo_centers",
    "Caco-2": "Caco2_Wang",
    "Bioavailability": "Bioavailability_Ma",
    "HIA": "HIA_Hou",
    "PAMPA": "PAMPA_NCATS",
    "Pgp": "Pgp_Broccatelli",
    "BBB penetration": "BBB_Martins",
    "VDss": "VDss_Lombardo",
    "PPBR": "PPBR_AZ",
    "CYP1A2 inhibitor": "CYP1A2_Veith",
    "CYP2C19 inhibitor": "CYP2C19_Veith",
    "CYP2C9 inhibitor": "CYP2C9_Veith",
    "CYP2D6 inhibitor": "CYP2D6_Veith",
    "CYP3A4 inhibitor": "CYP3A4_Veith",
    "CYP2C9 Substrate": "CYP2C9_Substrate_CarbonMangels",
    "CYP2D6 Substrate": "CYP2D6_Substrate_CarbonMangels",
    "CYP3A4 Substrate": "CYP3A4_Substrate_CarbonMangels",
    "Clearance (Microsome)": "Clearance_Microsome_AZ",
    "Clearance (Hepatocyte)": "Clearance_Hepatocyte_AZ",
    "Half Life": "Half_Life_Obach",
    "AMES": "AMES",
    "DILI": "DILI",
    "Carcinogenicity": "Carcinogens_Lagunin",
    "hERG": "hERG",
    "Skin Reaction": "Skin_Reaction",
    "LD50": "LD50_Zhu",
    "ClinTox": "ClinTox", 
    "NR-AR-LBD": "NR-AR-LBD",
    "NR-AR": "NR-AR",
    "NR-AhR": "NR-AhR",
    "NR-Aromatase": "NR-Aromatase",
    "NR-ER-LBD": "NR-ER-LBD",
    "NR-ER": "NR-ER", 
    "NR-PPAR-gamma": "NR-PPAR-gamma", 
    "SR-ARE": "SR-ARE", 
    "SR-ATAD5": "SR-ATAD5", 
    "SR-HSE": "SR-HSE", 
    "SR-MMP": "SR-MMP", 
    "SR-p53": "SR-p53"
}


map_columns_perc = {
    "Molecular Weight": "molecular_weight_drugbank_approved_percentile",
    "HBA": "hydrogen_bond_acceptors_drugbank_approved_percentile",
    "HBD": "hydrogen_bond_donors_drugbank_approved_percentile",
    "TPSA": "tpsa_drugbank_approved_percentile",
    "LogP": "logP_drugbank_approved_percentile",
    "Solubility": "Solubility_AqSolDB_drugbank_approved_percentile",
    "QED": "QED_drugbank_approved_percentile",
    "Stereo Centers": "stereo_centers_drugbank_approved_percentile",
    "Caco-2": "Caco2_Wang_drugbank_approved_percentile",
    "Bioavailability": "Bioavailability_Ma_drugbank_approved_percentile",
    "HIA": "HIA_Hou_drugbank_approved_percentile",
    "PAMPA": "PAMPA_NCATS_drugbank_approved_percentile",
    "Pgp": "Pgp_Broccatelli_drugbank_approved_percentile",
    "BBB penetration": "BBB_Martins_drugbank_approved_percentile",
    "VDss": "VDss_Lombardo_drugbank_approved_percentile",
    "PPBR": "PPBR_AZ_drugbank_approved_percentile",
    "CYP1A2 inhibitor": "CYP1A2_Veith_drugbank_approved_percentile",
    "CYP2C19 inhibitor": "CYP2C19_Veith_drugbank_approved_percentile",
    "CYP2C9 inhibitor": "CYP2C9_Veith_drugbank_approved_percentile",
    "CYP2D6 inhibitor": "CYP2D6_Veith_drugbank_approved_percentile",
    "CYP3A4 inhibitor": "CYP3A4_Veith_drugbank_approved_percentile",
    "CYP2C9 Substrate": "CYP2C9_Substrate_CarbonMangels_drugbank_approved_percentile",
    "CYP2D6 Substrate": "CYP2D6_Substrate_CarbonMangels_drugbank_approved_percentile",
    "CYP3A4 Substrate": "CYP3A4_Substrate_CarbonMangels_drugbank_approved_percentile",
    "Clearance (Microsome)": "Clearance_Microsome_AZ_drugbank_approved_percentile",
    "Clearance (Hepatocyte)": "Clearance_Hepatocyte_AZ_drugbank_approved_percentile",
    "Half Life": "Half_Life_Obach_drugbank_approved_percentile",
    "AMES": "AMES_drugbank_approved_percentile",
    "DILI": "DILI_drugbank_approved_percentile",
    "Carcinogenicity": "Carcinogens_Lagunin_drugbank_approved_percentile",
    "hERG": "hERG_drugbank_approved_percentile",
    "Skin Reaction": "Skin_Reaction_drugbank_approved_percentile",
    "LD50": "LD50_Zhu_drugbank_approved_percentile",
    "ClinTox": "ClinTox_drugbank_approved_percentile", 
    "NR-AR-LBD": "NR-AR-LBD_drugbank_approved_percentile",
    "NR-AR": "NR-AR_drugbank_approved_percentile",
    "NR-AhR": "NR-AhR_drugbank_approved_percentile",
    "NR-Aromatase": "NR-Aromatase_drugbank_approved_percentile",
    "NR-ER-LBD": "NR-ER-LBD_drugbank_approved_percentile",
    "NR-ER": "NR-ER_drugbank_approved_percentile", 
    "NR-PPAR-gamma": "NR-PPAR-gamma_drugbank_approved_percentile", 
    "SR-ARE": "SR-ARE_drugbank_approved_percentile", 
    "SR-ATAD5": "SR-ATAD5_drugbank_approved_percentile", 
    "SR-HSE": "SR-HSE_drugbank_approved_percentile", 
    "SR-MMP": "SR-MMP_drugbank_approved_percentile", 
    "SR-p53": "SR-p53_drugbank_approved_percentile"
}