[theme]
base="light"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="rgba(200, 229, 253, 1)"
codeBackgroundColor="#e0edfaff"

[theme.sidebar]
backgroundColor="#e8f1faff"
secondaryBackgroundColor="#D7E7F9"